In [1]:
import os
import gzip
import pandas as pd

# Image listings metadata
images_metadata_path = "/Users/harshit/Downloads/abo-images-small/images/metadata/images.csv.gz"

df_images = pd.read_csv(images_metadata_path, compression='gzip')

print("Shape:", df_images.shape)
print(df_images.head())

Shape: (398212, 4)
      image_id  height  width             path
0  010-mllS7JL     106    106  14/14fe8812.jpg
1  01dkn0Gyx0L     122    122  da/daab0cad.jpg
2  01sUPg0387L     111    111  d2/d2daaae9.jpg
3  1168jc-5r1L     186    186  3a/3a4e88e6.jpg
4  11RUV5Fs65L      30    500  d9/d91ab9cf.jpg

In [6]:
product_metadata_path = "/Users/harshit/Downloads/abo-listings/listings/metadata/listings_0.json.gz"

# Read the gzip-compressed JSON file
df_product = pd.read_json(product_metadata_path, compression='gzip', lines=True)

print("Shape:", df_product.shape)
display(df_product.columns)
display(df_product.head(5))

Shape: (9232, 28)

Index(['brand', 'bullet_point', 'color', 'item_id', 'item_name', 'model_name',
       'model_number', 'model_year', 'product_type', 'style', 'main_image_id',
       'other_image_id', 'item_keywords', 'country', 'marketplace',
       'domain_name', 'node', 'item_dimensions', 'item_weight', 'material',
       'fabric_type', 'color_code', 'product_description', 'spin_id',
       '3dmodel_id', 'pattern', 'finish_type', 'item_shape'],
      dtype='object')

,brand,bullet_point,color,item_id,item_name,model_name,model_number,model_year,product_type,style,...,item_weight,material,fabric_type,color_code,product_description,spin_id,3dmodel_id,pattern,finish_type,item_shape
0,"[{'language_tag': 'nl_NL', 'value': 'find.'}]","[{'language_tag': 'nl_NL', 'value': 'Schoen in...","[{'language_tag': 'nl_NL', 'value': 'Veelkleur...",B06X9STHNG,"[{'language_tag': 'nl_NL', 'value': 'Amazon-me...","[{'language_tag': 'nl_NL', 'value': '37753'}]",[{'value': '12-05-04'}],[{'value': 2017}],[{'value': 'SHOES'}],"[{'language_tag': 'nl_NL', 'value': 'Gesloten-...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'language_tag': 'es_MX', 'value': 'AmazonBas...","[{'language_tag': 'es_MX', 'value': 'White Pow...","[{'language_tag': 'es_MX', 'value': 'White Pow...",B07P8ML82R,"[{'language_tag': 'es_MX', 'value': '22"" Botto...",NaN,[{'value': 'AB5013-R22-10'}],NaN,[{'value': 'HARDWARE'}],"[{'language_tag': 'es_MX', 'value': '10 pares'}]",...,"[{'normalized_value': {'unit': 'pounds', 'valu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'language_tag': 'en_AE', 'value': 'AmazonBas...","[{'language_tag': 'en_AE', 'value': '3D printe...","[{'language_tag': 'en_AE', 'value': 'Transluce...",B07H9GMYXS,"[{'language_tag': 'en_AE', 'value': 'AmazonBas...",NaN,[{'value': 'AMG10528516-10'}],NaN,[{'value': 'MECHANICAL_COMPONENTS'}],"[{'language_tag': 'en_AE', 'value': '1-Pack'}]",...,"[{'normalized_value': {'unit': 'pounds', 'valu...","[{'language_tag': 'en_AE', 'value': 'PETG (Pol...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'language_tag': 'en_GB', 'value': 'Stone & B...",NaN,"[{'language_tag': 'en_GB', 'value': 'Stone Bro...",B07CTPR73M,"[{'language_tag': 'en_GB', 'value': 'Stone & B...",NaN,[{'value': '25020039-01'}],NaN,[{'value': 'SOFA'}],NaN,...,"[{'normalized_value': {'unit': 'pounds', 'valu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'language_tag': 'en_AU', 'value': 'The Fix'}]","[{'language_tag': 'en_AU', 'value': 'Embroider...","[{'language_tag': 'en_AU', 'standardized_value...",B01MTEI8M6,"[{'language_tag': 'en_AU', 'value': 'The Fix A...",NaN,[{'value': '880071Havana Tan'}],[{'value': 2017}],[{'value': 'SHOES'}],"[{'language_tag': 'en_AU', 'value': 'French Lo...",...,"[{'normalized_value': {'unit': 'pounds', 'valu...",NaN,"[{'language_tag': 'en_AU', 'value': 'Suede'}]",[#A67B5B],NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
display(df_product[['item_id','main_image_id']].head(5))

      item_id main_image_id
0  B06X9STHNG   81iZlv3bjpL
1  B07P8ML82R   619y9YG9cnL
2  B07H9GMYXS   81NP7qh2L6L
3  B07CTPR73M   61Rp4qOih9L
4  B01MTEI8M6   714CmIfKIYL

In [10]:
df_merged = df_product.merge(
    df_images,
    left_on="main_image_id",
    right_on="image_id",
    how="left"
)

display(df_merged.head(5))

,brand,bullet_point,color,item_id,item_name,model_name,model_number,model_year,product_type,style,...,product_description,spin_id,3dmodel_id,pattern,finish_type,item_shape,image_id,height,width,path
0,"[{'language_tag': 'nl_NL', 'value': 'find.'}]","[{'language_tag': 'nl_NL', 'value': 'Schoen in...","[{'language_tag': 'nl_NL', 'value': 'Veelkleur...",B06X9STHNG,"[{'language_tag': 'nl_NL', 'value': 'Amazon-me...","[{'language_tag': 'nl_NL', 'value': '37753'}]",[{'value': '12-05-04'}],[{'value': 2017}],[{'value': 'SHOES'}],"[{'language_tag': 'nl_NL', 'value': 'Gesloten-...",...,NaN,NaN,NaN,NaN,NaN,NaN,81iZlv3bjpL,2560.0,1969.0,8c/8ccb5859.jpg
1,"[{'language_tag': 'es_MX', 'value': 'AmazonBas...","[{'language_tag': 'es_MX', 'value': 'White Pow...","[{'language_tag': 'es_MX', 'value': 'White Pow...",B07P8ML82R,"[{'language_tag': 'es_MX', 'value': '22"" Botto...",NaN,[{'value': 'AB5013-R22-10'}],NaN,[{'value': 'HARDWARE'}],"[{'language_tag': 'es_MX', 'value': '10 pares'}]",...,NaN,NaN,NaN,NaN,NaN,NaN,619y9YG9cnL,1200.0,1200.0,9f/9f76d27b.jpg
2,"[{'language_tag': 'en_AE', 'value': 'AmazonBas...","[{'language_tag': 'en_AE', 'value': '3D printe...","[{'language_tag': 'en_AE', 'value': 'Transluce...",B07H9GMYXS,"[{'language_tag': 'en_AE', 'value': 'AmazonBas...",NaN,[{'value': 'AMG10528516-10'}],NaN,[{'value': 'MECHANICAL_COMPONENTS'}],"[{'language_tag': 'en_AE', 'value': '1-Pack'}]",...,NaN,NaN,NaN,NaN,NaN,NaN,81NP7qh2L6L,2492.0,2492.0,66/665cc994.jpg
3,"[{'language_tag': 'en_GB', 'value': 'Stone & B...",NaN,"[{'language_tag': 'en_GB', 'value': 'Stone Bro...",B07CTPR73M,"[{'language_tag': 'en_GB', 'value': 'Stone & B...",NaN,[{'value': '25020039-01'}],NaN,[{'value': 'SOFA'}],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,61Rp4qOih9L,500.0,500.0,b4/b4f9d0cc.jpg
4,"[{'language_tag': 'en_AU', 'value': 'The Fix'}]","[{'language_tag': 'en_AU', 'value': 'Embroider...","[{'language_tag': 'en_AU', 'standardized_value...",B01MTEI8M6,"[{'language_tag': 'en_AU', 'value': 'The Fix A...",NaN,[{'value': '880071Havana Tan'}],[{'value': 2017}],[{'value': 'SHOES'}],"[{'language_tag': 'en_AU', 'value': 'French Lo...",...,NaN,NaN,NaN,NaN,NaN,NaN,714CmIfKIYL,868.0,1779.0,2b/2b1c2516.jpg

In [17]:
# Drop products without a valid image path
df_merged = df_merged.dropna(subset=['path'])
# Full image path
base_img_dir = "/Users/harshit/Downloads/abo-images-small/images/small/"
df_merged['full_path'] = df_merged['path'].apply(lambda x: os.path.join(base_img_dir, x))

In [18]:
from PIL import Image
import os

In [25]:
# Get one product's image path
sample = df_merged.iloc[0]
img_path = os.path.join(base_img_dir, sample["path"])

print(f"Item Name: {sample['item_name'][0]['value']}")
print(f"Brand: {sample['brand'][0]['value']}")
print(f"Description: {sample['product_description']}")
print(f"Image path: {img_path}")

# Open image
img = Image.open(img_path)
img.show()

Item Name: Amazon-merk - vinden. Dames Leder Gesloten Teen Hakken,Veelkleurig Vrouw Blauw,5 UK
Brand: find.
Description: nan
Image path: /Users/harshit/Downloads/abo-images-small/images/small/8c/8ccb5859.jpg